artifact_location: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298
creation_time: 1698331528750
experiment_id: '548327397397163298'
last_update_time: 1698331528750
lifecycle_stage: active
name: NPL-Tweets
