artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298/168b1e839cee42349e03bae3d0f46fe7/artifacts
end_time: 1698684454262
entry_point_name: ''
experiment_id: '548327397397163298'
lifecycle_stage: active
run_id: 168b1e839cee42349e03bae3d0f46fe7
run_name: 1-Keras
run_uuid: 168b1e839cee42349e03bae3d0f46fe7
source_name: ''
source_type: 4
source_version: ''
start_time: 1698684428594
status: 3
tags: []
user_id: enric
