artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298/017f07e4caa840fc94eb78ecf81574e7/artifacts
end_time: 1698690836452
entry_point_name: ''
experiment_id: '548327397397163298'
lifecycle_stage: active
run_id: 017f07e4caa840fc94eb78ecf81574e7
run_name: Ada Boost Classifier
run_uuid: 017f07e4caa840fc94eb78ecf81574e7
source_name: ''
source_type: 4
source_version: ''
start_time: 1698690836192
status: 3
tags: []
user_id: enric
