artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298/f5460af69d8f46d7a71b6bde1335e982/artifacts
end_time: 1698687908432
entry_point_name: ''
experiment_id: '548327397397163298'
lifecycle_stage: active
run_id: f5460af69d8f46d7a71b6bde1335e982
run_name: 4_Keras
run_uuid: f5460af69d8f46d7a71b6bde1335e982
source_name: ''
source_type: 4
source_version: ''
start_time: 1698687882776
status: 3
tags: []
user_id: enric
