artifact_location: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/303098293392702791
creation_time: 1698594986370
experiment_id: '303098293392702791'
last_update_time: 1698595048315
lifecycle_stage: deleted
name: Pycaret_prueba_1
tags: {}
