artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/303098293392702791/ffda8b2cc1de460a8acba87bd0e73ff1/artifacts
deleted_time: 1698595048315
end_time: null
entry_point_name: ''
experiment_id: '303098293392702791'
lifecycle_stage: deleted
run_id: ffda8b2cc1de460a8acba87bd0e73ff1
run_name: Session Initialized f155
run_uuid: ffda8b2cc1de460a8acba87bd0e73ff1
source_name: ''
source_type: 4
source_version: ''
start_time: 1698594986405
status: 1
tags: []
user_id: enric
