artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298/f29597adc3a847ceb2ea35880f142c64/artifacts
end_time: null
entry_point_name: ''
experiment_id: '548327397397163298'
lifecycle_stage: active
run_id: f29597adc3a847ceb2ea35880f142c64
run_name: Session Initialized f087
run_uuid: f29597adc3a847ceb2ea35880f142c64
source_name: ''
source_type: 4
source_version: ''
start_time: 1698595295255
status: 1
tags: []
user_id: enric
