artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298/89a3bf48f6ba4e4eb1cfbd5e4adf08f0/artifacts
end_time: 1698684832337
entry_point_name: ''
experiment_id: '548327397397163298'
lifecycle_stage: active
run_id: 89a3bf48f6ba4e4eb1cfbd5e4adf08f0
run_name: 2-Keras
run_uuid: 89a3bf48f6ba4e4eb1cfbd5e4adf08f0
source_name: ''
source_type: 4
source_version: ''
start_time: 1698684799428
status: 3
tags: []
user_id: enric
