artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298/f944ceef72a042d1a5c73075b05f7e93/artifacts
end_time: null
entry_point_name: ''
experiment_id: '548327397397163298'
lifecycle_stage: active
run_id: f944ceef72a042d1a5c73075b05f7e93
run_name: Session Initialized 9903
run_uuid: f944ceef72a042d1a5c73075b05f7e93
source_name: ''
source_type: 4
source_version: ''
start_time: 1698595082426
status: 1
tags: []
user_id: enric
