artifact_uri: file:///c:/Users/enric/Documents/1 - Inteligencia Artificial/Proyectos/NPL-with-Disaster-Tweets/notebooks/2-Machine_Learning/../../mlflow/548327397397163298/be7dba15f7414933839df675bd20de75/artifacts
end_time: 1698690835633
entry_point_name: ''
experiment_id: '548327397397163298'
lifecycle_stage: active
run_id: be7dba15f7414933839df675bd20de75
run_name: Light Gradient Boosting Machine
run_uuid: be7dba15f7414933839df675bd20de75
source_name: ''
source_type: 4
source_version: ''
start_time: 1698690835385
status: 3
tags: []
user_id: enric
